import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { getLayout } from '../components/MainLayout/MainLayout'; // !important

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Here could be any content...</main>
    </div>
  );
};
Home.getLayout = getLayout; // !important

export default Home;
